
try:
    numero = int(input("Ingrese un n√∫mero:"))
except ValueError:
    print("Debe ingresar un valor entero")
except:
    print("No es el valor esperado")
finally:
    print("El bloque try ha finalizado")